### ISSUE TITLE
Direct user to the authorization web page response error code "3rd party bad request"

### ISSUE THREAD

**Issue by quiniton** [paypay/paypayopa-sdk-java#97]
[Direct user to the authorization web page](https://www.paypay.ne.jp/opa/doc/v1.0/link_user_web.html#section/Direct-user-to-the-authorization-web-page) response error code "3rd party bad request"

- Send requestToken 

```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJwYXlwYXkubmUuanAiLCJyZWRpcmVjdFVybCI6Imh0dHBzOi8vanAyLmhleS1wb3dlci5jb20iLCJzY29wZSI6ImRpcmVjdF9kZWJpdCxnZXRfYmFsYW5jZSIsImlzcyI6IjM0NDc2MTI0NzAzNzg5MDU2MCIsImV4cCI6MTYxNjA2NDY1Niwibm9uY2UiOiJ3aXp4aGN6MyIsImRldmljZUlkIjoiIiwicmVmZXJlbmNlSWQiOiJncXUzZGtlZCJ9.VNSR3HoJbVDRQSifVRK23NeN_zzZ_g7wwD3H1zPOm5E
```
- Open authorization page URL Response result 

```json
{"resultInfo":{"code":"3RD_PARTY_BAD_REQUEST","message":"3rd party bad request","codeId":"08100019"},"data":{"redirectUrl":"https://jp2.hey-power.com","validateClientRedirectParams":{"apiKey":"a_BBIC1QTmDc_9iu6","jwtToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXN1bHQiOiJiYWRfcmVxdWVzdCIsImF1ZCI6IjM0NDc2MTI0NzAzNzg5MDU2MCIsImlzcyI6InBheXBheS5uZS5qcCIsImV4cCI6MTYxNjAzNDYyMiwibm9uY2UiOiJ3aXp4aGN6MyIsInJlZmVyZW5jZUlkIjoiZ3F1M2RrZWQifQ.wt6R1OH3Xq7QYyeZhGm_Lsg6D31z3DKchLpJ-h_kYNs"}}}
```

- Use JWT debugger  requestToken decoded result
![image](https://user-images.githubusercontent.com/22997923/111563506-0cf27e80-87d3-11eb-9b8b-fea2b3d3100f.png)

**Comment by shreyanshp** [comment]
@javidlulu Please check this

**Comment by javidlulu** [comment]
@quiniton Since you are using java SDK,  I suggest to use the SDK library for this also so that you don't have to explicitly create request token and to avoid any errors in the request
Please check the link https://developer.paypay.ne.jp/products/docs/nativepayment, which explains the flow and code snippet.
You can check Acquire User Authorization section for this one.
Note that the scope to use is only direct_debit as explained in the document, get_balance is not to be added, which is the reason you got the error

Please let us know, for any further clarifications

**Comment by javidlulu** [comment]
Closing this issue as there is no response on the solution provided
